version: "3.8"

services:
    db:
        image: postgres:latest
        container_name: db_container
        environment:
            POSTGRES_DB: ecommerce
            POSTGRES_USER: root
            POSTGRES_PASSWORD: admin
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data

    app:
        container_name: backend
        build:
            dockerfile: Dockerfile
            context: .
        depends_on:
            - db
        env_file: ./.env
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - DB_USER=root
            - DB_PASSWORD=admin
            - DB_NAME=ecommerce
            - ENV=dev
            - SERVER_ADDRESS=0.0.0.0:8080
            - IS_LOGGING_TO_FILE=false
            - LOG_FILE_PATH=/var/log/backend.log
        ports:
            - 5000:8080

volumes:
    postgres-data:
